# Generated by Django 3.0.9 on 2020-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('CONS', 'Stomatologia zachowawcza'), ('ENDO', 'Endodoncja'), ('SURG', 'Chirurgia stomatologiczna'), ('PROS', 'Protetyka')], max_length=50)),
            ],
        ),
    ]
