# Generated by Django 3.0.9 on 2020-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'inquiries'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(default='default title', max_length=100),
            preserve_default=False,
        ),
    ]
